var Selfie=function(){function E(){var c="mirror"==m.data("type")?"&mirror={$type}":"",a=void 0;StorageManager.get("selfie_pics")?(b=JSON.parse(StorageManager.get("selfie_pics")),StorageManager.get("selfie_params")&&(d=JSON.parse(StorageManager.get("selfie_params"))),b.selfie&&(a=new Image,a.src=b.selfie.src,a.onload=function(){n.selfie.img=a;$("#selfie-tools").show();$("#selfie-functions").show();x=!0;q();k()})):b.house={};F();$("#selfie-type-"+b.placeholder.type).addClass("selected");b.house.src=
"/index.php?module=ajax&action=get_selfie_render&project_id="+m.data("id")+c;B()}function B(){var c=0;$.each(b,function(a,b){var e=void 0;"selfie"!=a&&(e=new Image,e.src=b.src,1==e.complete?(c++,n[a].img=e,3==c&&k()):e.onload=function(){c++;n[a].img=e;3==c&&k()})})}function G(){var c=$("#fileTrigger"),a=void 0;c[0].files&&c[0].files[0]&&("image/png"==c[0].files[0].type||"image/jpeg"==c[0].files[0].type||"image/gif"==c[0].files[0].type)?(a=new FileReader,a.onload=function(a){a=a.target.result;var c=
new Image;$("#uploadTrigger").hide();b.selfie={};b.selfie.src=a;c.src=a;c.onload=function(){n.selfie.img=c;b.selfie.width=c.width;b.selfie.height=c.height;if(c.width>=c.height){if(b.selfie.width>r.width){b.selfie.width=r.width;var a=b.selfie.width/c.width;b.selfie.height=parseInt(c.height*a)}}else b.selfie.height>r.height&&(b.selfie.height=r.height,a=b.selfie.height/c.height,b.selfie.width=parseInt(c.width*a));StorageManager.store("selfie_pics",JSON.stringify(b));StorageManager.store("selfie_params",
JSON.stringify(d));$("#selfie-tools").show();$("#selfie-functions").show();x=!0;y();q();k()}},a.readAsDataURL(c[0].files[0])):alert("B\u0142\u0119dny format pliku. Wgraj zdj\u0119cie o rozszerzeniu .jpg, .png lub .gif")}function H(c){c=$(c.target).parent("a");if(c.is("a")){var a=c.data("id");b.placeholder.type=a;b.placeholder.src="/img/selfie/mask"+a+"_placeholder.png";b.placeholder.offsetX=c.data("maskx");b.placeholder.offsetY=c.data("masky");b.mask.src="/img/selfie/mask"+a+".png";b.mask.midX=c.data("uploadx");
b.mask.midY=c.data("uploady");StorageManager.store("selfie_pics",JSON.stringify(b));y();B();q();$("#types-box a").removeClass("selected");c.addClass("selected")}}function I(){var c=void 0;c=void 0;k(!0);c=m[0].toDataURL("image/jpeg",.8);c=c.replace(/^data:image\/jpeg/,"data:application/octet-stream");$.ajax({url:"/index.php?module=selfie&action=upload",data:{project_id:$("#projectId").val(),generated_img:c,email:$("#selfieEmail").val(),name:$("#selfieName").val(),accept:$("#selfieAccept").val(),type_id:b.placeholder.type},
type:"post",dataType:"json",success:function(a){"ok"==a.status?($("#sendSelfie").hide(),alert("Twoje selfie zosta\u0142o wys\u0142ane na podany adres e-mail. Znajdziesz w nim wszystkie niezb\u0119dne informacje zwi\u0105zane z mo\u017cliwo\u015bci\u0105 publikacji b\u0105d\u017a usuwania wygenerowanego selfie.")):alert(a.message)}})}function k(c){var a=void 0;h.clearRect(0,0,C,D);h.save();if(x){h.drawImage(n.mask.img,b.placeholder.offsetX,b.placeholder.offsetY);h.save();h.globalCompositeOperation=
"source-in";var f=b.selfie.width*d.scaleX/2;var e=b.selfie.height*d.scaleY/2;h.translate(b.selfie.offsetX+f,b.selfie.offsetY+e);h.rotate(d.rotation);h.scale(d.scaleX,d.scaleY);h.drawImage(n.selfie.img,-f/d.scaleX,-e/d.scaleY,b.selfie.width,b.selfie.height);h.restore();if(0!=d.brightness||0!=d.contrast||0!=d.saturation){h.save();f=h.getImageData(b.selfie.offsetX,b.selfie.offsetY,b.selfie.width,b.selfie.height);if(0!=d.brightness){a=d.brightness;e=f.data;for(var g=0;g<e.length;g+=4)e[g]+=a,e[g+1]+=
a,e[g+2]+=a;a=f}if(0!=d.contrast){e=d.contrast;a=f.data;e=259*(e+255)/(255*(259-e));for(g=0;g<a.length;g+=4)a[g]=e*(a[g]-128)+128,a[g+1]=e*(a[g+1]-128)+128,a[g+2]=e*(a[g+2]-128)+128;a=f}if(0!=d.saturation){a=f.data;var l=1+d.saturation;e=.3086*(1-l)+l;g=.6094*(1-l);var k=.082*(1-l),m=.3086*(1-l),q=.6094*(1-l)+l,r=.082*(1-l),u=.3086*(1-l),y=.6094*(1-l);l=.082*(1-l)+l;for(var t,z,A,v,w,p=0;p<a.length;p+=4)t=a[p],z=a[p+1],A=a[p+2],v=e*t+g*z+k*A,w=m*t+q*z+r*A,t=u*t+y*z+l*A,a[p]=v,a[p+1]=w,a[p+2]=t;a=
f}h.putImageData(a,b.selfie.offsetX,b.selfie.offsetY);h.restore()}h.save();h.globalCompositeOperation="destination-atop";h.drawImage(n.placeholder.img,b.placeholder.offsetX,b.placeholder.offsetY);c&&h.drawImage(n.house.img,0,0);h.restore()}else h.drawImage(n.placeholder.img,b.placeholder.offsetX,b.placeholder.offsetY);h.restore()}function q(){if(x){var c=$("#selfie-box");var a=180*d.rotation/Math.PI;var f=d.scaleX*b.selfie.width;var e=d.scaleY*b.selfie.height;c.css({left:b.selfie.offsetX,top:b.selfie.offsetY,
width:f,height:e});c.css({MozTransform:"rotate("+a+"deg)"});c.css({WebkitTransform:"rotate("+a+"deg)"});c.css({"-o-transform":"rotate("+a+"deg)"});c.css({"-ms-transform":"rotate("+a+"deg)"});c.show();u();$("#selfie-controls").show()}}function J(){$("#rotate").draggable({start:function(){var c=b.selfie.width*d.scaleX,a=b.selfie.height*d.scaleY;this.props={x:b.selfie.offsetX+c/2,y:b.selfie.offsetY+a/2,width:c,height:a,offset:$("#canvas-box").offset(),angle:Math.atan2(a/2,c/2),radius:v(c,a)};$(this).siblings().hide()},
drag:function(b,a){var c=Math.atan2(b.pageY-this.props.offset.top-this.props.y,b.pageX-this.props.offset.left-this.props.x)+this.props.angle,e=180*c/Math.PI,g=$("#selfie-box");d.rotation=c;g.css({MozTransform:"rotate("+e+"deg)"});g.css({WebkitTransform:"rotate("+e+"deg)"});g.css({"-o-transform":"rotate("+e+"deg)"});g.css({"-ms-transform":"rotate("+e+"deg)"});a.position.left=Math.round(this.props.width/2+this.props.radius*Math.cos(Math.atan(this.props.height/this.props.width)-d.rotation))-10;a.position.top=
Math.round(this.props.height/2-this.props.radius*Math.sin(Math.atan(this.props.height/this.props.width)-d.rotation))-10;k()},stop:function(){StorageManager.store("selfie_params",JSON.stringify(d));u();$(this).siblings().show()}});$("#resize").draggable({start:function(){this.props={width:b.selfie.width*d.scaleX,height:b.selfie.height*d.scaleY,ratio:b.selfie.width*d.scaleX/(b.selfie.height*d.scaleY)};$(this).siblings().hide()},drag:function(c,a){if(w)if(1<=this.props.ratio){var f=this.props.width+
(a.position.left-a.originalPosition.left);24>f&&(f=24);var e=Math.round(f/this.props.ratio)}else e=this.props.height+(a.position.top-a.originalPosition.top),24>e&&(e=24),f=Math.round(e*this.props.ratio);else f=this.props.width+(a.position.left-a.originalPosition.left),e=this.props.height+(a.position.top-a.originalPosition.top);d.scaleX=f/b.selfie.width;d.scaleY=e/b.selfie.height;radius=v(f,e);a.position.left=Math.round(f/2+radius*Math.cos(Math.atan(e/f)+d.rotation))-10;a.position.top=Math.round(e/
2+radius*Math.sin(Math.atan(e/f)+d.rotation))-10;$("#selfie-box").css({width:f,height:e});k()},stop:function(){StorageManager.store("selfie_params",JSON.stringify(d));u();$(this).siblings().show();k()}});$("#selfie-box").draggable({start:function(c,a){$("#selfie-controls").hide();this.props={xoff:b.selfie.offsetX-a.position.left,yoff:b.selfie.offsetY-a.position.top}},drag:function(c,a){a.position.left+=this.props.xoff;a.position.top+=this.props.yoff;b.selfie.offsetX=a.position.left;b.selfie.offsetY=
a.position.top;k()},stop:function(c,a){StorageManager.store("selfie_pics",JSON.stringify(b));u();$("#selfie-controls").show()}})}function F(){$("#brightness").slider({value:d.brightness,min:-255,max:255,step:1,slide:function(){d.brightness=$(this).slider("value");StorageManager.store("selfie_params",JSON.stringify(d));k()}});$("#contrast").slider({value:d.contrast,min:-255,max:255,step:1,slide:function(){d.contrast=$(this).slider("value");StorageManager.store("selfie_params",JSON.stringify(d));k()}});
$("#saturation").slider({value:d.saturation,min:-1,max:1,step:.1,slide:function(){d.saturation=$(this).slider("value");StorageManager.store("selfie_params",JSON.stringify(d));k()}})}function y(){d.scaleX=1;d.scaleY=1;d.rotation=0;x&&(b.selfie.offsetX=b.placeholder.offsetX+b.mask.midX-b.selfie.width/2,b.selfie.offsetY=b.placeholder.offsetY+b.mask.midY-b.selfie.height/2);$("#brightness").slider("value",0);$("#contrast").slider("value",0);$("#saturation").slider("value",0)}function v(b,a){return Math.sqrt(Math.pow(b/
2,2)+Math.pow(a/2,2))}function u(){var c=b.selfie.width*d.scaleX;var a=b.selfie.height*d.scaleY,f=v(c,a);var e=[Math.round(a/2-f*Math.sin(Math.atan(a/c)-d.rotation)),Math.round(a/2+f*Math.sin(Math.atan(a/c)+d.rotation))];c=[Math.round(c/2+f*Math.cos(Math.atan(a/c)-d.rotation)),Math.round(c/2+f*Math.cos(Math.atan(a/c)+d.rotation))];a=$("#selfie-box");$("#selfie-controls").css({top:a.css("top"),left:a.css("left")});$("#rotate").css({top:e[0]-10,left:c[0]-10});$("#resize").css({top:e[1]-10,left:c[1]-
10})}var m=void 0,h=void 0,C=void 0,D=void 0,w=!0,x=!1,b={placeholder:{type:1,src:"/img/selfie/mask1_placeholder.png",offsetX:600,offsetY:150},mask:{src:"/img/selfie/mask1.png",midX:147,midY:142}},n={placeholder:{img:void 0},mask:{img:void 0},house:{img:void 0},selfie:{img:void 0}},r={width:380,height:380},d={scaleX:1,scaleY:1,rotation:0,brightness:0,contrast:0,saturation:0};$(document).ready(function(){m=$("#canvas");C=m.width();D=m.height();h=m.get(0).getContext("2d");$("#infoTrigger").click(function(){$("#infoBox").is(":hidden")?
$("#infoBox").fadeIn():$("#infoBox").fadeOut()});$("#types-box").on("click",H);$("#uploadTrigger").on("click",function(){$("#fileTrigger").click()});$("#reUpload").on("click",function(){$("#fileTrigger").click()});$("#proportionalTrigger").on("change",function(){w=!w});$("#fileTrigger").on("change",G);$("#selfie-reset").on("click",function(){y();q();k()});$("#save").on("click",function(){$("#selfie-tools").hide();$("#selfie-buttons").hide();$("#selfie-box").hide();$("#selfie-controls").hide();$("#saveForm").fadeIn()});
$("#backSelfie").on("click",function(){$("#selfie-tools").show();$("#selfie-buttons").show();$("#selfie-box").show();$("#selfie-controls").show();$("#saveForm").fadeOut()});$("#sendSelfie").on("click",I);J();E()})}();