(function(){var A=!1,G=!1;$(document).ready(function(){$("#road").selectmenu({appendTo:"#road-box"});$("#info-trigger").on("click",function(){A||(G?(A=!0,$("#info-txt").slideUp(500,function(){G=A=!1;$("#info-trigger").removeClass("on")})):(A=!0,$("#info-txt").slideDown(500,function(){A=!1;G=!0;$("#info-trigger").addClass("on")})))});$("#close-info").on("click",function(){A=!0;$("#info-txt").slideUp(500,function(){G=A=!1;$("#info-trigger").removeClass("on")})});$("#mobile-opts-trigger").on("click",
function(){$("#sketch-opts-wrapper").is(":visible")?($("#sketch-opts-wrapper").slideUp(),$(this).removeClass("on")):($("#sketch-opts-wrapper").slideDown(),$(this).addClass("on"))});enquire.register("screen and (max-width: 1160px)",{match:function(){$("#sketch-trigger").text(" ");$("#sun-trigger").text(" ")},unmatch:function(){$("#sketch-trigger").text("usytuowanie na dzia\u0142ce");$("#sun-trigger").text("do\u015bwietlenie");$("#print-box").show()}})})})();
var Canvas={CONTROL_DIAMETER:26,CONTROL_CENTER_OFFSET:13,IMG_CONTROL_CENTER_OFFSET:7,WIDTH_HEIGHT_RATIO:800/650};
Canvas.Plot=function(){function A(){p=$("#canvas-box").width();t=p/Canvas.WIDTH_HEIGHT_RATIO;650<t&&(t=650);$("#canvas-box").css("height",t);C.attr("width",p);C.attr("height",t);k=C.get(0).getContext("2d")}function G(b){I.width=parseFloat($("#plot-width").val().replace(",","."));I.height=parseFloat($("#plot-height").val().replace(",","."));m=I.height/(t-100);I.width>I.height&&I.width/m>p-100&&(m=I.width/(p-100));ca();b||W();K($("#road").val());D();$("#plot-controls").show()}function fa(){var b=JSON.parse(StorageManager.get("parcel")),
e=0,a=0;I=b.plot;m=b.ratio;f=b.controls;f.__proto__=new Hash;f.get(0).__proto__=new Props;f.get(1).__proto__=new Props;f.get(2).__proto__=new Props;f.get(3).__proto__=new Props;ca(b.positions);K(b.road);$("#plot-width").val(b.plot.width);$("#plot-height").val(b.plot.height);$("#road").val(b.road);$("#road").selectmenu("refresh");$("#"+b.version).prop("checked",!0);$("#plan-nav").data("id")==b.id?(n=b.img,n.__proto__=new Props,O(n.getProp("src")),X=b.storeys,1<X&&$("#storey-1-label").show(),2<X&&$("#storey-2-label").show()):
D();W();var d=L();b=Y();var g=d.xmax-d.xmin;d=d.ymax-d.ymin;if(d>t-100||g>p-100)d>t-100&&(e=d>b.h?(2*d-b.h)*m/(t-100):d*m/(t-100)),g>p-100&&(a=g>b.w?(2*g-b.w)*m/(p-100):g*m/(p-100)),a>e?P(a):P(e);$("#plot-controls").show()}function ca(b){var e=I.width/m,a=I.height/m,d=(p-e)/2,g=(t-a)/2;if(b){var h=f.get(0);$("#plot-controls").css({top:h.getProp("ys"),left:h.getProp("xs")});$("#p0").css({top:b[0][1],left:b[0][0]});$("#p1").css({top:b[1][1],left:b[1][0]});$("#p2").css({top:b[2][1],left:b[2][0]});$("#p3").css({top:b[3][1],
left:b[3][0]})}else f=new Hash,h=new Props,h.setProp("x",d),h.setProp("y",g),h.setProp("xs",d),h.setProp("ys",g),f.set(0,h),h=new Props,h.setProp("x",d+e),h.setProp("y",g),h.setProp("xs",d+e),h.setProp("ys",g),f.set(1,h),h=new Props,h.setProp("x",d+e),h.setProp("y",g+a),h.setProp("xs",d+e),h.setProp("ys",g+a),f.set(2,h),h=new Props,h.setProp("x",d),h.setProp("y",g+a),h.setProp("xs",d),h.setProp("ys",g+a),f.set(3,h),$("#plot-controls").css({top:g,left:d}),$("#p0").css({top:-Canvas.CONTROL_CENTER_OFFSET,
left:-Canvas.CONTROL_CENTER_OFFSET}),$("#p1").css({top:-Canvas.CONTROL_CENTER_OFFSET,left:e-Canvas.CONTROL_CENTER_OFFSET}),$("#p2").css({top:a-Canvas.CONTROL_CENTER_OFFSET,left:e-Canvas.CONTROL_CENTER_OFFSET}),$("#p3").css({top:a-Canvas.CONTROL_CENTER_OFFSET,left:-Canvas.CONTROL_CENTER_OFFSET})}function P(b){var e=1;b&&(e=m/b,m=b);var a=I.width/m;var d=I.height/m;var g=(p-a)/2;var h=(t-d)/2;$("#plot-controls").css({top:h,left:g});b=f.get(0);var l=(b.getProp("x")-b.getProp("xs"))*e;var B=(b.getProp("y")-
b.getProp("ys"))*e;b.setProp("x",g+l);b.setProp("y",h+B);b.setProp("xs",g);b.setProp("ys",h);$("#p0").css({top:B-Canvas.CONTROL_CENTER_OFFSET,left:l-Canvas.CONTROL_CENTER_OFFSET});b=f.get(1);l=(b.getProp("x")-b.getProp("xs"))*e;B=(b.getProp("y")-b.getProp("ys"))*e;b.setProp("x",g+a+l);b.setProp("y",h+B);b.setProp("xs",g+a);b.setProp("ys",h);$("#p1").css({top:B-Canvas.CONTROL_CENTER_OFFSET,left:a+l-Canvas.CONTROL_CENTER_OFFSET});b=f.get(2);l=(b.getProp("x")-b.getProp("xs"))*e;B=(b.getProp("y")-b.getProp("ys"))*
e;b.setProp("x",g+a+l);b.setProp("y",h+d+B);b.setProp("xs",g+a);b.setProp("ys",h+d);$("#p2").css({top:d+B-Canvas.CONTROL_CENTER_OFFSET,left:a+l-Canvas.CONTROL_CENTER_OFFSET});b=f.get(3);l=(b.getProp("x")-b.getProp("xs"))*e;B=(b.getProp("y")-b.getProp("ys"))*e;b.setProp("x",g+l);b.setProp("y",h+d+B);b.setProp("xs",g);b.setProp("ys",h+d);$("#p3").css({top:d+B-Canvas.CONTROL_CENTER_OFFSET,left:l-Canvas.CONTROL_CENTER_OFFSET});b=e;ys=xs=point=void 0;plotBounders=T();i=0;e="undefined"!==typeof da?da/m:
.0141/m;n.setProp("size",{width:H.width*e,height:H.height*e});n.setProp("scale",e);xs=plotBounders.xmin+(plotBounders.xmax-plotBounders.xmin-n.getProp("size").width)/2;ys=plotBounders.ymin+(plotBounders.ymax-plotBounders.ymin-n.getProp("size").height)/2;n.setProp("x",xs+(n.getProp("x")-n.getProp("xs"))*b);n.setProp("y",ys+(n.getProp("y")-n.getProp("ys"))*b);n.setProp("xs",xs);n.setProp("ys",ys);b=n.getProp("points");for(i=0;i<b.length;i++)point=b[i],point.x=point.xs*e,point.y=point.ys*e;b=n.getProp("mpoints");
for(i=0;i<b.length;i++)point=b[i],point.x=point.xs*e,point.y=point.ys*e;J.css({top:n.getProp("y"),left:n.getProp("x"),width:n.getProp("size").width-2,height:n.getProp("size").height-2});w();r();K($("#road").val());Canvas.Sun.setDirty(!0);Canvas.Sun.isActive()||v()}function W(){$("#plot-controls div").draggable({containment:"#canvas-box",start:function(b,e){var a=f.get($(this).data("idx"));this.props={idx:$(this).data("idx"),x:a.getProp("x"),y:a.getProp("y")}},drag:function(b,e){var a=f.get(this.props.idx);
a.setProp("x",this.props.x+e.position.left-e.originalPosition.left);a.setProp("y",this.props.y+e.position.top-e.originalPosition.top);switch(this.props.idx){case 0:a.getProp("x")>f.get(1).getProp("x")-Canvas.CONTROL_DIAMETER&&(a.setProp("x",f.get(1).getProp("x")-Canvas.CONTROL_DIAMETER),e.position.left=a.getProp("x")-a.getProp("xs")-Canvas.CONTROL_CENTER_OFFSET);a.getProp("y")>f.get(3).getProp("y")-Canvas.CONTROL_DIAMETER&&(a.setProp("y",f.get(3).getProp("y")-Canvas.CONTROL_DIAMETER),e.position.top=
a.getProp("y")-a.getProp("ys")-Canvas.CONTROL_CENTER_OFFSET);switch(c.side){case "N":var d=f.get(1);d=(a.getProp("y")-d.getProp("y"))/(a.getProp("x")-d.getProp("x"));var g=a.getProp("y")-d*a.getProp("x");var h=Math.cos(Math.atan(d));c.p1.x=c.p1.xs+a.getProp("x")-a.getProp("xs");c.p3.x=c.p3.xs+a.getProp("x")-a.getProp("xs");c.p5.x=c.p5.xs+a.getProp("x")-a.getProp("xs");Q(d,g,1,h,a.getProp("y")-a.getProp("ys"));break;case "W":d=f.get(3);d=(a.getProp("y")-d.getProp("y"))/(a.getProp("x")-d.getProp("x"));
g=a.getProp("y")-d*a.getProp("x");var l=Math.atan(d);h=Math.abs(Math.cos(l));c.p2.y=c.p2.ys+a.getProp("y")-a.getProp("ys");c.p4.y=c.p4.ys+a.getProp("y")-a.getProp("ys");c.p6.y=c.p6.ys+a.getProp("y")-a.getProp("ys");M(d,g,Math.sign(l),h,a.getProp("x")-a.getProp("xs"))}break;case 1:a.getProp("x")<f.get(0).getProp("x")+Canvas.CONTROL_DIAMETER&&(a.setProp("x",f.get(0).getProp("x")+Canvas.CONTROL_DIAMETER),e.position.left=a.getProp("x")-f.get(0).getProp("xs")-Canvas.CONTROL_CENTER_OFFSET);a.getProp("y")>
f.get(2).getProp("y")-Canvas.CONTROL_DIAMETER&&(a.setProp("y",f.get(2).getProp("y")-Canvas.CONTROL_DIAMETER),e.position.top=a.getProp("y")-a.getProp("ys")-Canvas.CONTROL_CENTER_OFFSET);switch(c.side){case "N":d=f.get(0);d=(d.getProp("y")-a.getProp("y"))/(d.getProp("x")-a.getProp("x"));g=a.getProp("y")-d*a.getProp("x");h=Math.cos(Math.atan(d));c.p2.x=c.p2.xs+a.getProp("x")-a.getProp("xs");c.p4.x=c.p4.xs+a.getProp("x")-a.getProp("xs");c.p6.x=c.p6.xs+a.getProp("x")-a.getProp("xs");Q(d,g,1,h,a.getProp("y")-
a.getProp("ys"));break;case "E":d=f.get(2),d=(a.getProp("y")-d.getProp("y"))/(a.getProp("x")-d.getProp("x")),g=a.getProp("y")-d*a.getProp("x"),l=Math.atan(d),h=Math.abs(Math.cos(l)),c.p1.y=c.p1.ys+a.getProp("y")-a.getProp("ys"),c.p3.y=c.p3.ys+a.getProp("y")-a.getProp("ys"),c.p5.y=c.p5.ys+a.getProp("y")-a.getProp("ys"),M(d,g,-Math.sign(l),h,a.getProp("x")-a.getProp("xs"))}break;case 2:a.getProp("x")<f.get(3).getProp("x")+Canvas.CONTROL_DIAMETER&&(a.setProp("x",f.get(3).getProp("x")+Canvas.CONTROL_DIAMETER),
e.position.left=a.getProp("x")-f.get(3).getProp("xs")-Canvas.CONTROL_CENTER_OFFSET);a.getProp("y")<f.get(1).getProp("y")+Canvas.CONTROL_DIAMETER&&(a.setProp("y",f.get(1).getProp("y")+Canvas.CONTROL_DIAMETER),e.position.top=a.getProp("y")-f.get(1).getProp("ys")-Canvas.CONTROL_CENTER_OFFSET);switch(c.side){case "S":d=f.get(3);d=(d.getProp("y")-a.getProp("y"))/(d.getProp("x")-a.getProp("x"));g=a.getProp("y")-d*a.getProp("x");h=Math.cos(Math.atan(d));c.p2.x=c.p2.xs+a.getProp("x")-a.getProp("xs");c.p4.x=
c.p4.xs+a.getProp("x")-a.getProp("xs");c.p6.x=c.p6.xs+a.getProp("x")-a.getProp("xs");Q(d,g,-1,h,a.getProp("y")-a.getProp("ys"));break;case "E":d=f.get(1),d=(a.getProp("y")-d.getProp("y"))/(a.getProp("x")-d.getProp("x")),g=a.getProp("y")-d*a.getProp("x"),l=Math.atan(d),h=Math.abs(Math.cos(l)),c.p2.y=c.p2.ys+a.getProp("y")-a.getProp("ys"),c.p4.y=c.p4.ys+a.getProp("y")-a.getProp("ys"),c.p6.y=c.p6.ys+a.getProp("y")-a.getProp("ys"),M(d,g,-Math.sign(l),h,a.getProp("x")-a.getProp("xs"))}break;case 3:switch(a.getProp("x")>
f.get(2).getProp("x")-Canvas.CONTROL_DIAMETER&&(a.setProp("x",f.get(2).getProp("x")-Canvas.CONTROL_DIAMETER),e.position.left=a.getProp("x")-a.getProp("xs")-Canvas.CONTROL_CENTER_OFFSET),a.getProp("y")<f.get(0).getProp("y")+Canvas.CONTROL_DIAMETER&&(a.setProp("y",f.get(0).getProp("y")+Canvas.CONTROL_DIAMETER),e.position.top=a.getProp("y")-f.get(0).getProp("ys")-Canvas.CONTROL_CENTER_OFFSET),c.side){case "S":d=f.get(2);d=(a.getProp("y")-d.getProp("y"))/(a.getProp("x")-d.getProp("x"));g=a.getProp("y")-
d*a.getProp("x");h=Math.cos(Math.atan(d));c.p1.x=c.p1.xs+a.getProp("x")-a.getProp("xs");c.p3.x=c.p3.xs+a.getProp("x")-a.getProp("xs");c.p5.x=c.p5.xs+a.getProp("x")-a.getProp("xs");Q(d,g,-1,h,a.getProp("y")-a.getProp("ys"));break;case "W":d=f.get(0),d=(a.getProp("y")-d.getProp("y"))/(a.getProp("x")-d.getProp("x")),g=a.getProp("y")-d*a.getProp("x"),l=Math.atan(d),h=Math.abs(Math.cos(l)),c.p1.y=c.p1.ys+a.getProp("y")-a.getProp("ys"),c.p3.y=c.p3.ys+a.getProp("y")-a.getProp("ys"),c.p5.y=c.p5.ys+a.getProp("y")-
a.getProp("ys"),M(d,g,Math.sign(l),h,a.getProp("x")-a.getProp("xs"))}}Z&&q(u());v()}})}function K(b){var e=I.width/m,a=I.height/m,d=(p-e)/2,g=(t-a)/2;switch(b){case "N":var h=f.get(0);var l=f.get(1);c.p1={xs:d-100,ys:g-5};c.p2={xs:d+e+100,ys:g-5};c.p3={xs:d-100,ys:g-15};c.p4={xs:d+e+100,ys:g-15};c.p5={xs:d-100,ys:g-25};c.p6={xs:d+e+100,ys:g-25};c.p1.x=c.p1.xs+h.getProp("x")-h.getProp("xs");c.p2.x=c.p2.xs+l.getProp("x")-l.getProp("xs");c.p3.x=c.p3.xs+h.getProp("x")-h.getProp("xs");c.p4.x=c.p4.xs+l.getProp("x")-
l.getProp("xs");c.p5.x=c.p5.xs+h.getProp("x")-h.getProp("xs");c.p6.x=c.p6.xs+l.getProp("x")-l.getProp("xs");e=(h.getProp("y")-l.getProp("y"))/(h.getProp("x")-l.getProp("x"));a=h.getProp("y")-e*h.getProp("x");l=Math.cos(Math.atan(e));Q(e,a,1,l,h.getProp("y")-h.getProp("ys"));break;case "E":h=f.get(1);l=f.get(2);c.p1={xs:d+e+5,ys:g-100};c.p2={xs:d+e+5,ys:g+a+100};c.p3={xs:d+e+15,ys:g-100};c.p4={xs:d+e+15,ys:g+a+100};c.p5={xs:d+e+25,ys:g-100};c.p6={xs:d+e+25,ys:g+a+100};c.p1.y=c.p1.ys+h.getProp("y")-
h.getProp("ys");c.p2.y=c.p2.ys+l.getProp("y")-l.getProp("ys");c.p3.y=c.p3.ys+h.getProp("y")-h.getProp("ys");c.p4.y=c.p4.ys+l.getProp("y")-l.getProp("ys");c.p5.y=c.p5.ys+h.getProp("y")-h.getProp("ys");c.p6.y=c.p6.ys+l.getProp("y")-l.getProp("ys");e=(h.getProp("y")-l.getProp("y"))/(h.getProp("x")-l.getProp("x"));a=h.getProp("y")-e*h.getProp("x");alpha=Math.atan(e);l=Math.abs(Math.cos(alpha));M(e,a,-Math.sign(alpha),l,h.getProp("x")-h.getProp("xs"));break;case "S":h=f.get(3);l=f.get(2);c.p1={xs:d-100,
ys:g+a+5};c.p2={xs:d+e+100,ys:g+a+5};c.p3={xs:d-100,ys:g+a+15};c.p4={xs:d+e+100,ys:g+a+15};c.p5={xs:d-100,ys:g+a+25};c.p6={xs:d+e+100,ys:g+a+25};c.p1.x=c.p1.xs+h.getProp("x")-h.getProp("xs");c.p2.x=c.p2.xs+l.getProp("x")-l.getProp("xs");c.p3.x=c.p3.xs+h.getProp("x")-h.getProp("xs");c.p4.x=c.p4.xs+l.getProp("x")-l.getProp("xs");c.p5.x=c.p5.xs+h.getProp("x")-h.getProp("xs");c.p6.x=c.p6.xs+l.getProp("x")-l.getProp("xs");e=(h.getProp("y")-l.getProp("y"))/(h.getProp("x")-l.getProp("x"));a=h.getProp("y")-
e*h.getProp("x");l=Math.cos(Math.atan(e));Q(e,a,-1,l,h.getProp("y")-h.getProp("ys"));break;case "W":h=f.get(0),l=f.get(3),c.p1={xs:d-5,ys:g+a+100},c.p2={xs:d-5,ys:g-100},c.p3={xs:d-15,ys:g+a+100},c.p4={xs:d-15,ys:g-100},c.p5={xs:d-25,ys:g+a+100},c.p6={xs:d-25,ys:g-100},c.p1.y=c.p1.ys+h.getProp("y")-h.getProp("ys"),c.p2.y=c.p2.ys+l.getProp("y")-l.getProp("ys"),c.p3.y=c.p3.ys+h.getProp("y")-h.getProp("ys"),c.p4.y=c.p4.ys+l.getProp("y")-l.getProp("ys"),c.p5.y=c.p5.ys+h.getProp("y")-h.getProp("ys"),c.p6.y=
c.p6.ys+l.getProp("y")-l.getProp("ys"),e=(h.getProp("y")-l.getProp("y"))/(h.getProp("x")-l.getProp("x")),a=h.getProp("y")-e*h.getProp("x"),alpha=Math.atan(e),l=Math.abs(Math.cos(alpha)),M(e,a,Math.sign(alpha),l,h.getProp("x")-h.getProp("xs"))}c.side=b;Z&&q(u())}function Q(b,e,a,d,g){0==b?(c.p1.y=c.p1.ys+g,c.p2.y=c.p2.ys+g,c.p3.y=c.p3.ys+g,c.p4.y=c.p4.ys+g,c.p5.y=c.p5.ys+g,c.p6.y=c.p6.ys+g):(c.p1.y=c.p1.ys+(c.p1.x-(c.p1.ys-e+5*a/d)/b)*b,c.p2.y=c.p2.ys+(c.p2.x-(c.p2.ys-e+5*a/d)/b)*b,c.p3.y=c.p3.ys+
(c.p3.x-(c.p3.ys-e+15*a/d)/b)*b,c.p4.y=c.p4.ys+(c.p4.x-(c.p4.ys-e+15*a/d)/b)*b,c.p5.y=c.p5.ys+(c.p5.x-(c.p5.ys-e+25*a/d)/b)*b,c.p6.y=c.p6.ys+(c.p6.x-(c.p6.ys-e+25*a/d)/b)*b)}function M(b,e,a,d,g){isFinite(b)?(c.p1.x=c.p1.xs+(c.p1.y-(b*c.p1.xs+e+5*a/d))/b,c.p2.x=c.p2.xs+(c.p2.y-(b*c.p2.xs+e+5*a/d))/b,c.p3.x=c.p3.xs+(c.p3.y-(b*c.p3.xs+e+15*a/d))/b,c.p4.x=c.p4.xs+(c.p4.y-(b*c.p4.xs+e+15*a/d))/b,c.p5.x=c.p5.xs+(c.p5.y-(b*c.p5.xs+e+25*a/d))/b,c.p6.x=c.p6.xs+(c.p6.y-(b*c.p6.xs+e+25*a/d))/b):(c.p1.x=c.p1.xs+
g,c.p2.x=c.p2.xs+g,c.p3.x=c.p3.xs+g,c.p4.x=c.p4.xs+g,c.p5.x=c.p5.xs+g,c.p6.x=c.p6.xs+g)}function D(){$.ajax({url:"/index.php?module=project_extend&action=get_situation",data:{id:$("#plan-nav").data("id")},type:"post",dataType:"json",success:function(b){"ok"==b.status&&(1<b.storeys&&$("#storey-1-label").show(),2<b.storeys&&$("#storey-2-label").show(),X=b.storeys,y(b))}})}function y(b){H=new Image;H.src=b.image;1==H.complete?N(b):H.onload=function(){N(b)}}function O(b){H=new Image;H.src=b;1==H.complete?
R():H.onload=function(){R()}}function N(b){var e=[],a=[],d=void 0;var g=T();if("undefined"!==typeof b.plot_ratio){da=b.plot_ratio;var h=da/m}else h=.0141/m;n=new Props("img");n.setProp("src",b.image);n.setProp("size",{width:H.width*h,height:H.height*h});n.setProp("scale",h);var l=g.xmin+(g.xmax-g.xmin-n.getProp("size").width)/2;g=g.ymin+(g.ymax-g.ymin-n.getProp("size").height)/2;n.setProp("x",l);n.setProp("y",g);n.setProp("xs",l);n.setProp("ys",g);n.setProp("rot",0);b=jQuery.parseJSON(b.situation.corner_points);
for(d in b)e.push({x:b[d].x*h,y:b[d].y*h,xs:b[d].x,ys:b[d].y}),a.push({x:(H.width-b[d].x)*h,y:b[d].y*h,xs:H.width-b[d].x,ys:b[d].y});n.setProp("points",e);n.setProp("mpoints",a);R()}function R(){var b=180*n.getProp("rot")/Math.PI;J.css({top:n.getProp("y"),left:n.getProp("x"),width:n.getProp("size").width-2,height:n.getProp("size").height-2});J.css({MozTransform:"rotate("+b+"deg)"});J.css({WebkitTransform:"rotate("+b+"deg)"});J.css({"-o-transform":"rotate("+b+"deg)"});J.css({"-ms-transform":"rotate("+
b+"deg)"});J.css({transform:"rotate("+b+"deg)"});w();r();aa();U()}function U(){ba=0==$("#normal").size()||"normal"==$("#sketch-opts-box input[type=radio]:checked").val()?!0:!1;Z=!0;$("#controls").show();J.show();q(u());v()}function V(){Z&&U();Canvas.Sun.setDirty(!0)}function aa(){$("#img-box").draggable({containment:"#canvas-box",start:function(b,e){$("#controls").hide();this.props={xoff:n.getProp("x")-e.position.left,yoff:n.getProp("y")-e.position.top,lines:u()}},drag:function(b,e){e.position.left+=
this.props.xoff;e.position.top+=this.props.yoff;n.setProp("x",e.position.left);n.setProp("y",e.position.top);q(this.props.lines);v()},stop:function(){w();r();$("#controls").show()}});$("#rotate").draggable({start:function(){var b=n.getProp("size").width,e=n.getProp("size").height;this.props={x:n.getProp("x")+b/2,y:n.getProp("y")+e/2,angle:Math.atan2(e/2,b/2),radius:Canvas.Helper.getRadius(b,e),lines:u(),offset:$("#canvas-box").offset()}},drag:function(b,e){var a=n.getProp("size").width,d=n.getProp("size").height;
$("#canvas-box").offset();var g=Math.atan2(b.pageY-this.props.offset.top-this.props.y,b.pageX-this.props.offset.left-this.props.x)+this.props.angle,h=180*g/Math.PI;n.setProp("rot",g);J.css({MozTransform:"rotate("+h+"deg)"});J.css({WebkitTransform:"rotate("+h+"deg)"});J.css({"-o-transform":"rotate("+h+"deg)"});J.css({"-ms-transform":"rotate("+h+"deg)"});J.css({transform:"rotate("+h+"deg)"});q(this.props.lines);e.position.left=a/2+this.props.radius*Math.cos(Math.atan(d/a)-n.getProp("rot"))-Canvas.IMG_CONTROL_CENTER_OFFSET;
e.position.top=d/2-this.props.radius*Math.sin(Math.atan(d/a)-n.getProp("rot"))-Canvas.IMG_CONTROL_CENTER_OFFSET;v()},stop:function(){Canvas.Sun.setDirty(!0)}})}function L(){var b,e={xmin:p,xmax:0,ymin:t,ymax:0};for(b=0;b<f.size();b++){var a=f.get(b);a.getProp("x")<e.xmin&&(e.xmin=a.getProp("x"));a.getProp("x")>e.xmax&&(e.xmax=a.getProp("x"));a.getProp("y")<e.ymin&&(e.ymin=a.getProp("y"));a.getProp("y")>e.ymax&&(e.ymax=a.getProp("y"))}return e}function T(){var b,e={xmin:p,xmax:0,ymin:t,ymax:0};for(b=
0;b<f.size();b++){var a=f.get(b);a.getProp("xs")<e.xmin&&(e.xmin=a.getProp("xs"));a.getProp("xs")>e.xmax&&(e.xmax=a.getProp("xs"));a.getProp("ys")<e.ymin&&(e.ymin=a.getProp("ys"));a.getProp("ys")>e.ymax&&(e.ymax=a.getProp("ys"))}return e}function Y(){var b={w:0,h:0};var e=f.get(0);var a=f.get(2);b.w=a.getProp("xs")-e.getProp("xs");b.h=a.getProp("ys")-e.getProp("ys");return b}function w(){$("#controls").css({top:n.getProp("y"),left:n.getProp("x")})}function r(){var b=n.getProp("size").width;var e=
n.getProp("size").height,a=e/b,d=n.getProp("rot"),g=Canvas.Helper.getRadius(b,e);e=[e/2-Math.floor(g*Math.sin(Math.atan(a)+d)),e/2-Math.floor(g*Math.sin(Math.atan(a)-d)),e/2+Math.ceil(g*Math.sin(Math.atan(a)+d)),e/2+Math.ceil(g*Math.sin(Math.atan(a)-d))];b=[b/2-Math.floor(g*Math.cos(Math.atan(a)+d)),b/2+Math.ceil(g*Math.cos(Math.atan(a)-d)),b/2+Math.ceil(g*Math.cos(Math.atan(a)+d)),b/2-Math.floor(g*Math.cos(Math.atan(a)-d))];$("#rotate").css({top:e[1]-Canvas.IMG_CONTROL_CENTER_OFFSET,left:b[1]-Canvas.IMG_CONTROL_CENTER_OFFSET})}
function u(){var b=4/m,e=6/m,a={N:{},E:{},S:{},W:{}};margin="N"==c.side?e:b;var d=f.get(0);var g=f.get(1);a.N.a=(d.getProp("y")-g.getProp("y"))/(d.getProp("x")-g.getProp("x"));a.N.b=d.getProp("y")-a.N.a*d.getProp("x")+margin/Math.cos(Math.atan(a.N.a));margin="E"==c.side?e:b;d=f.get(2);g=f.get(1);a.E.a=(d.getProp("y")-g.getProp("y"))/(d.getProp("x")-g.getProp("x"));a.E.b=d.getProp("y")-a.E.a*d.getProp("x")+Math.sign(a.E.a)*margin/Math.cos(Math.atan(a.E.a));margin="S"==c.side?e:b;d=f.get(3);g=f.get(2);
a.S.a=(d.getProp("y")-g.getProp("y"))/(d.getProp("x")-g.getProp("x"));a.S.b=d.getProp("y")-a.S.a*d.getProp("x")-margin/Math.cos(Math.atan(a.S.a));margin="W"==c.side?e:b;d=f.get(3);g=f.get(0);a.W.a=(d.getProp("y")-g.getProp("y"))/(d.getProp("x")-g.getProp("x"));a.W.b=d.getProp("y")-a.W.a*d.getProp("x")-Math.sign(a.W.a)*margin/Math.cos(Math.atan(a.W.a));return a}function q(b){var e=n.getProp("size").width,a=n.getProp("size").height,d=n.getProp("rot"),g=ba?n.getProp("points"):n.getProp("mpoints"),h=
4/m,l=6/m,B;F.N=!1;F.E=!1;F.S=!1;F.W=!1;for(B=0;B<g.length;B++){var E=e/2+((g[B].x-e/2)*Math.cos(d)-(g[B].y-a/2)*Math.sin(d));var ea=a/2+((g[B].x-e/2)*Math.sin(d)+(g[B].y-a/2)*Math.cos(d));if(!F.N){var S=b.N.a*(n.getProp("x")+E)+b.N.b;n.getProp("y")+ea<S?F.N=!0:F.N=!1}F.E||(isFinite(b.E.a)?S=(n.getProp("y")+ea-b.E.b)/b.E.a:(margin="E"==c.side?l:h,S=f.get(1).getProp("x")-margin),n.getProp("x")+E>S?F.E=!0:F.E=!1);F.S||(S=b.S.a*(n.getProp("x")+E)+b.S.b,n.getProp("y")+ea>S?F.S=!0:F.S=!1);F.W||(isFinite(b.W.a)?
S=(n.getProp("y")+ea-b.W.b)/b.W.a:(margin="W"==c.side?l:h,S=f.get(0).getProp("x")+margin),n.getProp("x")+E<S?F.W=!0:F.W=!1)}}function x(){var b={id:$("#plan-nav").data("id"),plot:I,ratio:m,controls:f,positions:{0:[$("#p0").css("left"),$("#p0").css("top")],1:[$("#p1").css("left"),$("#p1").css("top")],2:[$("#p2").css("left"),$("#p2").css("top")],3:[$("#p3").css("left"),$("#p3").css("top")]},road:$("#road").val(),img:n,version:ba?"normal":"mirror",storeys:X};StorageManager.store("parcel",JSON.stringify(b))}
function z(){$("#img-data").val(C[0].toDataURL());$("#plot-print-form").submit()}function v(){var b=void 0;var e=[];var a=4/m;var d=6/m;var g;k.clearRect(0,0,C.attr("width"),C.attr("height"));k.save();var h=Math.atan((f.get(1).getProp("y")-f.get(0).getProp("y"))/(f.get(1).getProp("x")-f.get(0).getProp("x")));var l=Math.atan((f.get(1).getProp("y")-f.get(2).getProp("y"))/(f.get(1).getProp("x")-f.get(2).getProp("x")));var B=Math.atan((f.get(2).getProp("y")-f.get(3).getProp("y"))/(f.get(2).getProp("x")-
f.get(3).getProp("x")));var E=Math.atan((f.get(0).getProp("y")-f.get(3).getProp("y"))/(f.get(0).getProp("x")-f.get(3).getProp("x")));for(g=0;g<f.size();g++)switch(g){case 0:k.moveTo(f.get(g).getProp("x"),f.get(g).getProp("y"));break;default:k.lineTo(f.get(g).getProp("x"),f.get(g).getProp("y"))}k.clip();for(b in F)F[b]?e.push(b):e.unshift(b);for(g=0;g<e.length;g++)switch(e[g]){case "N":b="N"==c.side?d:a;k.beginPath();k.moveTo(f.get(0).getProp("x"),f.get(0).getProp("y"));k.lineTo(f.get(1).getProp("x"),
f.get(1).getProp("y"));k.lineTo(f.get(1).getProp("x")+b/Math.sin(l-h)*Math.cos(l),f.get(1).getProp("y")+b/Math.sin(l-h)*Math.sin(l));k.lineTo(f.get(0).getProp("x")+b/Math.sin(E-h)*Math.cos(E),f.get(0).getProp("y")+b/Math.sin(E-h)*Math.sin(E));k.fillStyle=F.N?"#ff9595":"#93ceff";k.fill();break;case "E":b="E"==c.side?d:a;k.beginPath();k.moveTo(f.get(2).getProp("x"),f.get(2).getProp("y"));k.lineTo(f.get(1).getProp("x"),f.get(1).getProp("y"));k.lineTo(f.get(1).getProp("x")-b/Math.sin(l-h)*Math.sign(l)*
Math.cos(h),f.get(1).getProp("y")-b/Math.sin(l-h)*Math.sign(l)*Math.sin(h));k.lineTo(f.get(2).getProp("x")-b/Math.sin(l-B)*Math.sign(l)*Math.cos(B),f.get(2).getProp("y")-b/Math.sin(l-B)*Math.sign(l)*Math.sin(B));k.fillStyle=F.E?"#ff9595":"#93ceff";k.fill();break;case "S":b="S"==c.side?d:a;k.beginPath();k.moveTo(f.get(2).getProp("x"),f.get(2).getProp("y"));k.lineTo(f.get(3).getProp("x"),f.get(3).getProp("y"));k.lineTo(f.get(3).getProp("x")-b/Math.sin(E-B)*Math.cos(E),f.get(3).getProp("y")-b/Math.sin(E-
B)*Math.sin(E));k.lineTo(f.get(2).getProp("x")-b/Math.sin(l-B)*Math.cos(l),f.get(2).getProp("y")-b/Math.sin(l-B)*Math.sin(l));k.fillStyle=F.S?"#ff9595":"#93ceff";k.fill();break;case "W":b="W"==c.side?d:a,k.beginPath(),k.moveTo(f.get(3).getProp("x"),f.get(3).getProp("y")),k.lineTo(f.get(0).getProp("x"),f.get(0).getProp("y")),k.lineTo(f.get(0).getProp("x")+b/Math.sin(E-h)*Math.sign(E)*Math.cos(h),f.get(0).getProp("y")+b/Math.sin(E-h)*Math.sign(E)*Math.sin(h)),k.lineTo(f.get(3).getProp("x")+b/Math.sin(E-
B)*Math.sign(E)*Math.cos(B),f.get(3).getProp("y")+b/Math.sin(E-B)*Math.sign(E)*Math.sin(B)),k.fillStyle=F.W?"#ff9595":"#93ceff",k.fill()}k.restore();k.save();k.beginPath();k.lineWidth=2;for(g=0;g<f.size();g++)switch(g){case 0:k.moveTo(f.get(g).getProp("x"),f.get(g).getProp("y"));break;default:k.lineTo(f.get(g).getProp("x"),f.get(g).getProp("y"))}k.closePath();k.strokeStyle="#8fa6ae";k.stroke();k.beginPath();k.moveTo(c.p1.x,c.p1.y);k.lineTo(c.p2.x,c.p2.y);k.lineTo(c.p6.x,c.p6.y);k.lineTo(c.p5.x,c.p5.y);
k.fillStyle="#8fa6ae";k.fill();k.setLineDash([10,15]);k.beginPath();k.moveTo(c.p3.x,c.p3.y);k.lineTo(c.p4.x,c.p4.y);k.strokeStyle="#ffffff";k.stroke();k.restore();for(g=0;g<f.size();g++){k.save();k.font="12px Open Sans";k.fillStyle="#005fad";d=f.get(g);b=3==g?f.get(0):f.get(g+1);a=Math.sqrt(Math.pow(b.getProp("x")-d.getProp("x"),2)+Math.pow(b.getProp("y")-d.getProp("y"),2));a=Math.round(a*m*100)/100;e=k.measureText(a+" m").width;switch(g){case 0:k.translate(d.getProp("x")+(b.getProp("x")-d.getProp("x"))/
2-20*Math.sin(h),d.getProp("y")+(b.getProp("y")-d.getProp("y"))/2+20*Math.cos(h));k.rotate(h);k.fillText(a+" m",-e/2,0);break;case 1:k.translate(d.getProp("x")+(b.getProp("x")-d.getProp("x"))/2-20*Math.sign(l)*Math.sin(l),d.getProp("y")+(b.getProp("y")-d.getProp("y"))/2+20*Math.sign(l)*Math.cos(l));k.rotate(l);k.fillText(a+" m",-e/2,0);break;case 2:k.translate(d.getProp("x")+(b.getProp("x")-d.getProp("x"))/2+20*Math.sin(B),d.getProp("y")+(b.getProp("y")-d.getProp("y"))/2-20*Math.cos(B));k.rotate(B);
k.fillText(a+" m",-e/2,0);break;case 3:k.translate(d.getProp("x")+(b.getProp("x")-d.getProp("x"))/2+20*Math.sign(E)*Math.sin(E),d.getProp("y")+(b.getProp("y")-d.getProp("y"))/2-20*Math.sign(E)*Math.cos(E)),k.rotate(E),k.fillText(a+" m",-e/2,0)}k.restore()}Z&&(k.save(),h=n.getProp("size").width/2,l=n.getProp("size").height/2,k.translate(n.getProp("x")+h,n.getProp("y")+l),k.rotate(n.getProp("rot")),ba||k.scale(-1,1),k.drawImage(H,-h,-l,n.getProp("size").width,n.getProp("size").height),k.restore())}
var C=void 0,k=void 0,p=void 0,t=void 0,f=void 0,m=void 0,da=void 0,H=void 0,n=void 0,J=void 0,ba=!0,Z=!1,I={},c={},F={N:!1,E:!1,S:!1,W:!1},X=void 0,ha=void 0;$(document).ready(function(){$("input.num").on("keydown",Canvas.Helper.numericCheck);$("#size-trigger").on("click",G);$("#road").selectmenu({change:function(b,e){K($("#road").val());v()}});$("#reset-trigger").on("click",function(b){$("#plot-width").val("25");$("#plot-height").val("40");$("#road").val("N");$("#road").selectmenu("refresh");$("#normal").prop("checked",
!0);StorageManager.remove("parcel");Canvas.Sun.setDirty(!0);G(b)});$("#sketch-opts-box input[type=radio]").on("change",V);$("#print-trigger").on("click",z);$("#save-trigger").on("click",x);J=$("#img-box");C=$("#canvas");A();StorageManager.get("parcel")?fa():G()});$(window).resize(function(b){window.clearTimeout(ha);ha=window.setTimeout(function(){var e=L(),a=Y(),d=e.xmax-e.xmin;e=e.ymax-e.ymin;var g=0;A();(e>t-100||d>p-100)&&e>t-100&&(g=e>a.h?(2*e-a.h)*m/(t-100):e*m/(t-100));(e<t-100||d<p-100)&&e<
t-100&&(g=e>a.h?(2*e-a.h)*m/(t-100):e*m/(t-100));P(g)},250)});return{getContext:function(){return k},getImage:function(){return H},getRotation:function(){return n.getProp("rot")},isMirror:function(){return!ba},redraw:v}}();
Canvas.Sun=function(){function A(){R||(L=R=!0,!1===$("#storey-0").is(":checked")&&$("#storey-0").click(),U=Canvas.Plot.isMirror(),D||(D={y:$("#canvas-box").height()-75,x:($("#canvas-box").width()-150)/2},$("#sun").css({top:D.y,left:D.x})),$("#print-box").hide(),$("#plot-controls").hide(),$("#img-box").hide(),$("#controls").hide(),$("#storey-box").show(),$("#sketch-opts-box").hide(),$("#sun").show(),$("#timer").show(),$("#sketch-trigger").removeClass("on"),$("#sun-trigger").addClass("on"),$("#sun-trigger-bottom").addClass("on"),
T?W():(M(),P(),K()))}function G(){$("#mobile-trigger-box").is(":visible")||$("#print-box").show();$("#canvas-box div.room").remove();$("#storey-box").hide();$("#sun").hide();$("#timer").hide();$("#sketch-opts-box").show();$("#plot-controls").show();$("#img-box").show();$("#controls").show();$("#sun-trigger").removeClass("on");$("#sun-trigger-bottom").removeClass("on");$("#sketch-trigger").addClass("on");Canvas.Plot.redraw();T=R=!1}function fa(w){w=$(this);"storey-0"==this.id?(L=!0,M(),P(),K()):(L=
!1,T||aa!=w.val()?($("#storey-loader").show(),aa=w.val(),Q(aa)):(M(),P(),K()))}function ca(w){V=new Image;V.src=w;1==V.complete?(K(),$("#storey-loader").hide()):V.onload=function(){K();$("#storey-loader").hide()}}function P(){var w,r,u=L?O:N,q=u.getKeys(),x=[],z=void 0,v=0;for(w=0;w<q.length;w++){var C=0;if(u.get(q[w]).lines){for(r=0;r<u.get(q[w]).lines.length;r++){var k=q[w];var p=r;p=L?O.get(k).lines[p]:N.get(k).lines[p];var t=void 0,f=0;L?O.get(k).exLine&&(t=O.get(k).exLine):N.get(k).exLine&&(t=
N.get(k).exLine);t&&Math.sqrt(Math.pow(D.x-t.p1ax,2)+Math.pow(D.y-t.p1ay,2))<Math.sqrt(Math.pow(D.x-t.p2ax,2)+Math.pow(D.y-t.p2ay,2))&&0>(t.a*D.x-D.y+t.b)*(t.a*t.acx-t.acy+t.b)?k=-1:(isFinite(p.a)?0<(p.a*D.x-D.y+p.b)*(p.a*p.acx-p.acy+p.b)&&(k=(D.y-p.acy)/(D.x-p.acx),f=Math.atan(Math.abs((k-p.a)/(1+k*p.a))),f=180*f/Math.PI/100):(p.acx>p.p1ax&&D.x>p.acx&&(k=(D.y-p.acy)/(D.x-p.acx),f=Math.atan(k),f=(90-180*f/Math.PI)/100),p.acx<p.p1ax&&D.x<p.acx&&(k=(D.y-p.acy)/(D.x-p.acx),f=Math.atan(k),f=(180*f/Math.PI+
90)/100)),k=f);if(-1==k){C=0;break}else C+=k}if(0<C){.9<C&&(C=.9);if(!x[q[w]]||x[q[w]]&&x[q[w]]<C)x[q[w]]=C;for(z in u.get(q[w]).related){switch(u.get(q[w]).related[z]){case "1":v=1;break;case "2":v=.6;break;case "3":v=.3}if(!x[z]||x[z]&&x[z]<C*v)x[z]=C*v}}else x[q[w]]||(x[q[w]]=0)}}for(w=0;w<q.length;w++)C=x[q[w]]||0,$("#room-"+q[w]).css({opacity:C})}function W(){var w=Canvas.Plot.getImage(),r=1,u=Canvas.Plot.getRotation(),q=$("#canvas-box").width(),x=$("#canvas-box").height()-80;var z=w.height*
Math.abs(Math.cos(u))+w.width*Math.abs(Math.sin(u));var v=w.height*Math.abs(Math.sin(u))+w.width*Math.abs(Math.cos(u));y=new Props("img");z>x&&(r=x/z);v>.6*q&&(z=.6*q/v,z<r&&(r=z));y.setProp("size",{width:w.width*r,height:w.height*r});y.setProp("scale",r);y.setProp("x",(q-w.width*r)/2);y.setProp("y",5+(x-w.height*r)/2);y.setProp("rot",u);Q(0);K()}function K(){var w=Canvas.Plot.getImage(),r=Canvas.Plot.getContext();r.clearRect(0,0,$("#canvas-box").width(),$("#canvas-box").height());r.save();var u=
y.getProp("size").width/2;var q=y.getProp("size").height/2;r.translate(y.getProp("x")+u,y.getProp("y")+q);r.rotate(y.getProp("rot"));U&&r.scale(-1,1);L?r.drawImage(w,-u,-q,y.getProp("size").width,y.getProp("size").height):r.drawImage(V,-u,-q,y.getProp("size").width,y.getProp("size").height);r.restore()}function Q(w){$.ajax({url:"/index.php?module=project_extend&action=get_rooms",data:{id:$("#plan-nav").data("id"),storey:w},type:"post",dataType:"json",success:function(r){if("ok"==r.status){var u=void 0,
q=y.getProp("size").width,x=y.getProp("size").height,z=y.getProp("scale"),v=y.getProp("rot"),C;for(u in r.rooms){var k={x:r.rooms[u].position_x*z,y:r.rooms[u].position_y*z,w:r.rooms[u].width*z,h:r.rooms[u].height*z};U&&(k.x=q-k.x-k.w);var p=k.x-q/2;var t=k.y-x/2;var f=p*Math.cos(v)-t*Math.sin(v);p=p*Math.sin(v)+t*Math.cos(v);k.ax=y.getProp("x")+f+q/2;k.ay=y.getProp("y")+p+x/2;for(C=0;C<r.rooms[u].lines_cords.length;C++){0==C&&(k.lines=[]);var m={p1x:r.rooms[u].lines_cords[C].p1.x*z,p1y:r.rooms[u].lines_cords[C].p1.y*
z,p2x:r.rooms[u].lines_cords[C].p2.x*z,p2y:r.rooms[u].lines_cords[C].p2.y*z,cx:r.rooms[u].lines_cords[C].pc.x*z,cy:r.rooms[u].lines_cords[C].pc.y*z};U&&(m.p1x=q-m.p1x,m.p2x=q-m.p2x,m.cx=q-m.cx);p=m.cx-q/2;t=m.cy-x/2;f=p*Math.cos(v)-t*Math.sin(v);p=p*Math.sin(v)+t*Math.cos(v);m.acx=y.getProp("x")+f+q/2;m.acy=y.getProp("y")+p+x/2;p=m.p1x-q/2;t=m.p1y-x/2;f=p*Math.cos(v)-t*Math.sin(v);p=p*Math.sin(v)+t*Math.cos(v);m.p1ax=y.getProp("x")+f+q/2;m.p1ay=y.getProp("y")+p+x/2;p=m.p2x-q/2;t=m.p2y-x/2;f=p*Math.cos(v)-
t*Math.sin(v);p=p*Math.sin(v)+t*Math.cos(v);m.p2ax=y.getProp("x")+f+q/2;m.p2ay=y.getProp("y")+p+x/2;m.a=(m.p1ay-m.p2ay)/(m.p1ax-m.p2ax);m.b=m.p1ay-(m.p1ay-m.p2ay)/(m.p1ax-m.p2ax)*m.p1ax;k.lines.push(m)}r.rooms[u].exclude_lines&&(m={p1x:r.rooms[u].exclude_lines.p1.x*z,p1y:r.rooms[u].exclude_lines.p1.y*z,p2x:r.rooms[u].exclude_lines.p2.x*z,p2y:r.rooms[u].exclude_lines.p2.y*z,cx:r.rooms[u].exclude_lines.cp.x*z,cy:r.rooms[u].exclude_lines.cp.y*z},U&&(m.p1x=q-m.p1x,m.p2x=q-m.p2x,m.cx=q-m.cx),p=m.cx-q/
2,t=m.cy-x/2,f=p*Math.cos(v)-t*Math.sin(v),p=p*Math.sin(v)+t*Math.cos(v),m.acx=y.getProp("x")+f+q/2,m.acy=y.getProp("y")+p+x/2,p=m.p1x-q/2,t=m.p1y-x/2,f=p*Math.cos(v)-t*Math.sin(v),p=p*Math.sin(v)+t*Math.cos(v),m.p1ax=y.getProp("x")+f+q/2,m.p1ay=y.getProp("y")+p+x/2,p=m.p2x-q/2,t=m.p2y-x/2,f=p*Math.cos(v)-t*Math.sin(v),p=p*Math.sin(v)+t*Math.cos(v),m.p2ax=y.getProp("x")+f+q/2,m.p2ay=y.getProp("y")+p+x/2,m.a=(m.p1ay-m.p2ay)/(m.p1ax-m.p2ax),m.b=m.p1ay-(m.p1ay-m.p2ay)/(m.p1ax-m.p2ax)*m.p1ax,k.exLine=
m);k.related=r.rooms[u].related_rooms;0==w?O.set(r.rooms[u].id,k):(N.set(r.rooms[u].id,k),T=!1)}M();P();0<w&&ca(r.image)}}})}function M(){var w=L?O:N,r=w.getKeys(),u=y.getProp("rot"),q=180*u/Math.PI,x;$("#canvas-box .room").remove();for(x=0;x<r.length;x++){var z=w.get(r[x]);var v=$(document.createElement("div")).attr("id","room-"+r[x]).addClass("room");v.css({top:z.ay,left:z.ax,width:z.w,height:z.h,transformOrigin:"top left"});0!=u&&(v.css({MozTransform:"rotate("+q+"deg)"}),v.css({WebkitTransform:"rotate("+
q+"deg)"}),v.css({"-o-transform":"rotate("+q+"deg)"}),v.css({"-ms-transform":"rotate("+q+"deg)"}),v.css({transform:"rotate("+q+"deg)"}));$("#canvas-box").append(v)}}var D=void 0,y=void 0,O=void 0,N=void 0,R=!1,U=!1,V=void 0,aa=void 0,L=!0,T=!0,Y=void 0;$(document).ready(function(){$("#sun-trigger").on("click",A);$("#sun-trigger-bottom").on("click",A);$("#sketch-trigger").on("click",G);$("#storey-box input").on("change",fa);O=new Hash;N=new Hash;$("#sun").draggable({start:function(){this.props={offset:$("#canvas-box").offset(),
width:$("#canvas-box").width(),height:$("#canvas-box").height()}},drag:function(w,r){var u=w.pageX-this.props.offset.left;50>u?u=50:u>this.props.width-50&&(u=this.props.width-50);var q=720*(this.props.width-50-u)/(this.props.width-100);var x=Math.floor(q/60)+6;q=Math.floor(q%60);10>q&&(q="0"+q);$("#time").html(x+":"+q);x=(75*(1-Math.abs(u-this.props.width/2)/(this.props.width/2))+75)/2;r.position.left=u-x;r.position.top=-((2*this.props.height+320)/Math.pow(this.props.width,2))*Math.pow(u,2)+(2*this.props.height+
320)/this.props.width*u+(this.props.height/2-80)-x;$("#sun").css({width:2*x,height:2*x});D.x=r.position.left+x;D.y=r.position.top+x;P()}})});$(window).resize(function(w){window.clearTimeout(Y);Y=window.setTimeout(function(){R&&(D={y:$("#canvas-box").height()-75,x:($("#canvas-box").width()-150)/2},$("#sun").css({top:D.y,left:D.x}),W(),K())},250)});return{isActive:function(){return R},setDirty:function(w){T=w}}}();
Canvas.Helper=function(){return{getRadius:function(A,G){return Math.sqrt(Math.pow(A/2,2)+Math.pow(G/2,2))},numericCheck:function(A){return-1<$.inArray(A.keyCode,[0,8,9,37,39,46,110,188,190])||48<=A.keyCode&&57>=A.keyCode||96<=A.keyCode&&105>=A.keyCode?!0:!1}}}();function Hash(){this.hash={}}Hash.prototype.set=function(A,G){this.hash[A]=G};Hash.prototype.unset=function(A){delete this.hash[A]};Hash.prototype.get=function(A){return this.hash[A]};Hash.prototype.size=function(){return Object.keys(this.hash).length};
Hash.prototype.getKeys=function(){return Object.keys(this.hash)};function Props(A){this.props={};this.props.id=A}Props.prototype.setProp=function(A,G){this.props[A]=G};Props.prototype.removeProp=function(A){delete this.props[A]};Props.prototype.getProp=function(A){return this.props[A]};